name: PR

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
env:
  RUBY_VERSION: 2.7.2
  TERRAFORM_VERSION: 0.14.7

jobs:
  format:
    name: Terraform-Format
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true

  test:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GEMFILE_DIR: .
      AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
      TF_VAR_region: eu-west-1
      TF_VAR_vpc_cidr_block: "10.0.0.0/16"
      TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Setup bundler
        uses: ./.github/actions/setup-bundler-for-testing
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Build and Test
        run: |
          bundle install
          kitchen converge hybrid-external-database | sed "s/${{ secrets.AWS_ACCOUNT }}/REDACTED/g"
          kitchen verify hybrid-external-database | sed "s/${{ secrets.AWS_ACCOUNT }}/REDACTED/g"
          echo "Kitchen logs:"
          sed "s/${{ secrets.AWS_ACCOUNT }}/REDACTED/g" .kitchen/logs/hybrid-external-database-local.log
        continue-on-error: true
      - name: Teardown
        run: kitchen destroy hybrid-external-database sed "s/${{ secrets.AWS_ACCOUNT }}/REDACTED/g"
