name: PR

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
env:
  TERRAFORM_VERSION: 0.14.7

jobs:
  format:
    name: Terraform-Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

  kics-scan:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: KICS Github Action
        uses: checkmarx/kics-action@docker-runner
        with:
          path: 'repo'
          output_path: 'results.json'
          platform_type: terraform
      - name: Display KICS Results
        run: |
          cat results.json

  check-aws-credentials:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Test AWS Credentials
        uses: docker://amazon/aws-cli
        with:
          args: ec2 describe-availability-zones --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}

  test:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: check-aws-credentials
    env:
      GEMFILE_DIR: .
      AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
      TF_VAR_region: eu-west-1
      TF_VAR_vpc_cidr_block: "10.0.0.0/16"
      TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Kitchen Test Ubuntu
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test hybrid-http-proxy --destroy=always
          aws-account-number: ${{ secrets.AWS_ACCOUNT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
          TF_VAR_region: eu-west-1
          TF_VAR_environment: GHA-${{ env.GITHUB_RUN_NUMBER }}
          TF_VAR_vpc_cidr_block: "10.0.0.0/16"
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
      - name: Kitchen Test Amazon linux 2
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test hybrid-amazon-linux --destroy=always
          aws-account-number: ${{ secrets.AWS_ACCOUNT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
          TF_VAR_region: eu-west-1
          TF_VAR_environment: GHA-${{ env.GITHUB_RUN_NUMBER }}
          TF_VAR_vpc_cidr_block: "10.0.0.0/16"
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
      - name: Deactivate AWS Credentials
        if: ${{ always() }}
        uses: docker://amazon/aws-cli
        with:
          args: iam update-access-key --access-key-id ${{ secrets.ACTIONS_ACCESS_KEY_ID }} --status Inactive
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
