name: PR

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
env:
  TERRAFORM_VERSION: 0.14.7

jobs:
  format:
    name: Terraform-Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

  kics-scan:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: KICS Github Action
        uses: checkmarx/kics-action@v1.4
        with:
          path: 'repo'
          exclude_paths: 'repo/examples'
          output_path: 'results'
          platform_type: terraform
          fail_on: high,medium
          exclude_queries: '8e94dced-9bcc-4203-8eb7-7e41202b2505,e592a0c5-5bdb-414c-9066-5dba7cdea370,7ebc9038-0bde-479a-acc4-6ed7b6758899' # Excludes 'Auto Scaling Group With No Associated ELB', 'IAM Access Analyzer Undefined' queries and Vulnerable policy for the KMS Key.
      - name: Display KICS Results
        run: |
          cat results/results.json

  docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: check-aws-credentials
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to AWS ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          password: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker-image
          build-args: 'KONG=2.8.1.1'
          push: true
          tags: |
            ghcr.io/dwp/terraform-aws-kong-gateway:${{ github.run_number }}
            ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.eu-west-1.amazonaws.com/terraform-aws-kong-gateway:${{ github.run_number }}

  check-aws-credentials:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Test AWS Credentials
        uses: docker://amazon/aws-cli
        with:
          args: ec2 describe-availability-zones --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}

  test:
    name: Kitchen-Terraform
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: check-aws-credentials
    env:
      GEMFILE_DIR: .
      AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
      TF_VAR_region: eu-west-1
      TF_VAR_vpc_cidr_block: "10.0.0.0/16"
      TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Kitchen Test Ubuntu
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test hybrid-http-proxy --destroy=always
          aws-account-number: ${{ secrets.AWS_ACCOUNT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
          TF_VAR_region: eu-west-1
          TF_VAR_environment: GHA-${{ env.GITHUB_RUN_NUMBER }}
          TF_VAR_vpc_cidr_block: "10.0.0.0/16"
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
      - name: Kitchen Test Amazon Linux 2
        uses: dwp/github-action-kitchen-terraform@0.14.7
        with:
          kitchen-command: test hybrid-amazon-linux --destroy=always
          aws-account-number: ${{ secrets.AWS_ACCOUNT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
          TF_VAR_region: eu-west-1
          TF_VAR_environment: GHA-${{ env.GITHUB_RUN_NUMBER }}
          TF_VAR_vpc_cidr_block: "10.0.0.0/16"
          TF_VAR_kong_database_password: ${{ secrets.KONG_DATABASE_PASSWORD }}
      - name: Deactivate AWS Credentials
        if: ${{ always() }}
        uses: docker://amazon/aws-cli
        with:
          args: iam update-access-key --access-key-id ${{ secrets.ACTIONS_ACCESS_KEY_ID }} --status Inactive
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
